projectName: Observatory
containerRepositories: northamerica-northeast1-docker.pkg.dev/phx-01h1yptgmche7jcy01wzzpw2rf/hello-world-app
serviceUrls:
  - safeinputs.phac.alpha.canada.ca/
  - safeinputs.phac.alpha.canada.ca/graphql
  - https://hopic-sdpac.phac-aspc.alpha.canada.ca/
  - https://hopic-sdpac.k8s.phac-aspc.alpha.canada.ca/login/?next=http%3A%2F%2Fhopic-sdpac.k8s.phac-aspc.alpha.canada.ca%2F
domains:
  - entreessecurisees.aspc.alpha.canada.ca
  - safeinputs.phac-aspc.alpha.canada.ca
  - safeinputs.phac.alpha.canada.ca
