# https://docs.docker.com/network/drivers/bridge/
# https://forums.docker.com/t/simple-cross-container-communication/33457/4
version: '1'
services:
  database:
    image: arangodb
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=yourpassword

  nats:
    image: nats:latest
    # name: nats-server
    # expose:
    #   - "4222"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    # hostname: nats.ruok

  api:
    build: ./api
    ports:
      - 4000:4000
    depends_on:
      - nats
      - database

networks:
  default:
    name: ruok
    external: true

