apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
# From arrangodb k8s operator: https://github.com/arangodb/kube-arangodb/tree/master
- https://raw.githubusercontent.com/arangodb/kube-arangodb/master/manifests/kustomize/all/arango-all.yaml