apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./arangodeployment-single-server.yaml
- ./deployment-nats.yaml
- ./deployment-ruok-api.yaml
- ./deployment-webhook-server.yaml
- ./nats-svc.yaml
# From arrangodb k8s operator: https://github.com/arangodb/kube-arangodb/tree/master
- https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.33/manifests/arango-crd.yaml
- https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.33/manifests/arango-deployment.yaml