apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: cert-manager
spec:
  dnsNames: []
  issuerRef:
    kind: Issuer
    # name: letsencrypt-staging
    name: letsencrypt
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: tlskeys
