apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- issuers.yaml
- certificate.yaml
patches:
- target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: ingress-cert
    namespace: cert-manager
  patch: |-
    - op: add
      path: /spec/dnsNames/-
      value: observatory.phac.alpha.canada.ca
- target:
    group: cert-manager.io
    version: v1
    kind: Issuer
    name: letsencrypt
    namespace: cert-manager
  patch: |-
    - op: add
      path: /spec/acme/solvers/-
      value:
        dns01:
          cloudDNS:
            project: phx-01h4rr1468rj3v5k60b1vserd3
- target:
    group: cert-manager.io
    version: v1
    kind: Issuer
    name: letsencrypt
    namespace: cert-manager
  patch: |-
    - op: add
      path: /spec/acme/email
      value: collin.brown@phac-aspc.gc.ca
