apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
patches:
- target:
    version: v1
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
  patch: |-
    - op: add
      path: "/metadata/annotations"
      value:
        iam.gke.io/gcp-service-account: dns01-solver@phx-01h8eq9sbx7d19zsvqk7t9zymr.iam.gserviceaccount.com